import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link';


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <header>
        <nav style={{display: 'flex',gap: '1rem'}}>
          <ul><Link href='/home'>Home</Link></ul>
          <ul><Link href='/dashboard'>Dashboard</Link></ul>
          <ul><Link href='/profile'>profile</Link></ul>
          <ul><Link href='/courses'>courses</Link></ul>
          <ul><Link href='/class'>class</Link></ul>
          <ul><Link href='/about'>about us</Link></ul>
          <ul><Link href='/location'>locations</Link></ul>
        </nav>
      </header>
        <div>Side bar</div>
        <div>
          <main>
            {children}
          </main>
        </div>
        <footer>
          <h1>Page footer</h1>
        </footer>
      </body>
    </html>
  )
}
